services:
  cat-health-api:
    container_name: cat-health-api
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
      network: host
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data:Z
      - ./recordings:/app/recordings:Z
    env_file:
      - ./.env
    restart: unless-stopped
